services:

  postgres:
    image: postgres:13-alpine3.20
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=e@mail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    restart: always
    depends_on: 
      - postgres